# Generated by Django 5.1.6 on 2025-03-06 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to=settings.AUTH_USER_MODEL),
        ),
    ]
