# Generated by Django 5.1.6 on 2025-03-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0002_alter_giver_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=150)),
                ('job_posted_date', models.DateField(auto_now=True)),
                ('job_time_shift', models.CharField(max_length=50)),
                ('job_discription', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience_requiered', models.TextField()),
                ('company_details', models.TextField()),
                ('recruiter_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjctapp.giver')),
            ],
        ),
    ]
