# Generated by Django 5.1.6 on 2025-04-17 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0006_rename_recruiter_details_saved_seeker_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='job_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjctapp.jobvacancy'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='seeker_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjctapp.seeker'),
        ),
    ]
