# Generated by Django 5.1.6 on 2025-04-17 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0008_alter_saved_job_details_alter_saved_seeker_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Resume', models.FileField(upload_to='')),
                ('portifolio_link', models.CharField()),
                ('cover_letter', models.TextField()),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.jobvacancy')),
            ],
        ),
    ]
