# Generated by Django 5.1.6 on 2025-04-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0009_applyforjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyforjob',
            name='job_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjctapp.jobvacancy'),
        ),
    ]
