# Generated by Django 5.1.6 on 2025-05-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0010_alter_applyforjob_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_message', models.CharField(blank=True, max_length=200, null=True)),
                ('seeker_message', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prjctapp.jobvacancy')),
                ('recruiter_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prjctapp.giver')),
                ('seeker_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prjctapp.seeker')),
            ],
        ),
    ]
