# Generated by Django 5.1.6 on 2025-05-05 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0011_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='recruiter_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prjctapp.giver'),
        ),
    ]
