# Generated by Django 5.1.6 on 2025-05-06 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0012_alter_jobvacancy_recruiter_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOfJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.jobvacancy')),
                ('seeker_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.seeker')),
            ],
        ),
    ]
