# Generated by Django 5.1.6 on 2025-05-06 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0013_statusofjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='job_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.jobvacancy'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recruiter_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.giver'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recruiter_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='seeker_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.seeker'),
        ),
        migrations.AlterField(
            model_name='message',
            name='seeker_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
