# Generated by Django 5.1.6 on 2025-05-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0014_alter_message_job_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofjob',
            name='seeker_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.applyforjob'),
        ),
    ]
