# Generated by Django 5.1.6 on 2025-05-07 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0015_alter_statusofjob_seeker_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofjob',
            name='seeker_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prjctapp.seeker'),
        ),
        migrations.AlterField(
            model_name='statusofjob',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Hired'), (2, 'Not Selected')], default=0),
        ),
    ]
