# Generated by Django 5.1.6 on 2025-05-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0016_alter_statusofjob_seeker_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyforjob',
            name='seeker_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prjctapp.seeker'),
        ),
    ]
