# Generated by Django 5.1.6 on 2025-05-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0017_applyforjob_seeker_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusofjob',
            name='apply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prjctapp.applyforjob'),
            preserve_default=False,
        ),
    ]
