# Generated by Django 5.1.6 on 2025-05-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prjctapp', '0018_statusofjob_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusofjob',
            name='apply',
        ),
    ]
